version: '3.8'

services:
  backend:
    env_file: ./backend/.env.docker  
    build:
      context: ./backend
    ports:
      - "3000:3000"
    container_name: "backend-container-image"
    environment:
      NODE_ENV: production

  frontend:
    env_file: ./frontend/.env.docker
    build:
      context: ./frontend
    ports:
      - "5173:80"
    container_name: "frontend-container-image"
    
